#!/usr/bin/env bash
if [ "$2" == "clone" ]; then
  git clone https://github.com/clean-docker/Magento2.git $1 && cd $1;
fi

git config --global core.autocrlf false
git config --global core.eol LF
git config --global core.fileMode false
git config --global diff.renamelimit 5000

sudo chmod u+x ./*

# docker image pull rafaelcgstz/magento2

sed -i '' -e "s/<project_name>/$1/g" docker-compose.yml;

bash start
