#!/usr/bin/env bash

if [ ! -d "src" ]; then
  git clone git@github.com:Bleez/magento-dev-pacotes.git src
fi

NOME_PASTA=${PWD##*/}

sudo chmod u+x install kill logs shell start stop update

rm -f .env docker-compose.yml \
      shell \
      image/bin/install-magento \
      config/nginx.conf \
      image/bin/redis-flush \
      image/extras/env.sample.php \

cp samples/docker-compose.sample.yml docker-compose.yml
cp samples/.env.sample .env
cp samples/shell.sample shell
cp samples/install-magento.sample image/bin/install-magento
cp samples/redis-flush.sample image/bin/redis-flush
cp samples/nginx.sample.conf config/nginx.conf
cp samples/env.sample.php image/extras/env.sample.php

sed -i '' -e "s/<projeto>/$NOME_PASTA/g" \
          docker-compose.yml \
          shell \
          image/bin/install-magento \
          image/bin/redis-flush \
          image/extras/env.sample.php \
          config/nginx.conf;

sed -i '' -e  "s#<path-local>#$PWD#g" .env;

if [ "$(uname)" == "Darwin" ]; then
  sed -i '' -e "s/\${REMOTE_HOST}/host.docker.internal/g" docker-compose.yml;
fi

echo "Concluído. Para iniciar execute ./start"
