#!/usr/bin/env bash
docker-compose -f docker-compose.yml -f docker-compose.custom.yml  up -d
echo "
===================== 🚀 Done 🚀 ===================

      Created by Bruno Viana 😎
      Access your new links:

      🌎 Web server: http://127.0.0.1/
      ⚙️ PHPMyAdmin: http://127.0.0.1:8080
      ✉️ Local emails: http://127.0.0.1:8025

===================== 🚀 Done 🚀 ==================="
